#!/bin/bash

echo "🚀 FoodBridge Deployment Options"
echo "==============================="
echo ""
echo "Railway (Recommended - FREE):"
echo "1. Go to https://railway.app"
echo "2. Connect your GitHub account"
echo "3. Import the foodbridge repository"
echo "4. Railway will auto-deploy with all configurations"
echo ""
echo "Render (Alternative - FREE):"
echo "1. Go to https://render.com"
echo "2. Create new Web Service"
echo "3. Connect your GitHub repo (kedarrpandya/foodbridge)"
echo "4. Use these settings:"
echo "   - Runtime: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "5. Add environment variables from render.yaml"
echo ""
echo "Vercel (Frontend + API - FREE):"
echo "1. Go to https://vercel.com"
echo "2. Import the foodbridge repository"
echo "3. Vercel will auto-detect and deploy"
echo ""
echo "Manual Docker (Local/Production):"
echo "docker compose up --build -d"
echo ""
echo "📝 Your app will be live at:"
echo "- Railway: https://foodbridge.up.railway.app"
echo "- Render: https://foodbridge.onrender.com"
echo "- Vercel: https://foodbridge.vercel.app"
echo ""
echo "🔧 Don't forget to add your OpenAI API key in environment variables!"
